# Data-access layer for Domain rows in PostgreSQL.
# Services talk to this class instead of touching the SQLAlchemy Session directly.
from sqlalchemy.orm import Session

from app.models.sql_models import Domain


class DomainRepository:
    def __init__(self, db: Session):
        self.db = db

    def create(self, name: str, url: str) -> Domain:
        domain = Domain(name=name, url=url)
        self.db.add(domain)
        self.db.commit()
        self.db.refresh(domain)  # populate id/created_at generated by the DB
        return domain

    def get(self, domain_id: int) -> Domain | None:
        return self.db.get(Domain, domain_id)

    def get_by_name(self, name: str) -> Domain | None:
        return self.db.query(Domain).filter(Domain.name == name).first()

    def list(self, active_only: bool = False) -> list[Domain]:
        query = self.db.query(Domain)
        if active_only:
            query = query.filter(Domain.is_active.is_(True))
        return query.order_by(Domain.id).all()

    def delete(self, domain: Domain) -> None:
        # cascade="all, delete-orphan" on Domain.checks also removes its check history
        self.db.delete(domain)
        self.db.commit()
